# Generated by Django 4.2.1 on 2025-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamVidDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Mac Address')),
                ('TimeStart', models.TimeField(blank=True, null=True, verbose_name='On time')),
                ('TimeEnd', models.TimeField(blank=True, null=True, verbose_name='Off time')),
                ('SleepTime', models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time')),
                ('is_continous', models.BooleanField(default=False, verbose_name='continuous?')),
                ('refresh', models.IntegerField(blank=True, choices=[(10, '10 s'), (20, '20 s'), (60, '60 s')], default=10, null=True, verbose_name='Sampling Rate')),
                ('saveImage', models.BooleanField(default=False, verbose_name='save Image?')),
                ('runningNN', models.BooleanField(default=False, verbose_name='running NN?')),
            ],
            options={
                'verbose_name': 'Cam video device',
                'verbose_name_plural': 'Cam video devices',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('Normal running', 'Normal running'), ('Low battery', 'Low battery'), ('No signal', 'No signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=1800, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'Environmental device',
                'verbose_name_plural': 'Environmental devices',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Gateway Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Gateway Mac Address')),
                ('TimeStart', models.TimeField(blank=True, null=True, verbose_name='On time')),
                ('TimeEnd', models.TimeField(blank=True, null=True, verbose_name='Off time')),
                ('SleepTime', models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time')),
            ],
            options={
                'verbose_name': 'Gateway device',
                'verbose_name_plural': 'Gateway devices',
            },
        ),
        migrations.CreateModel(
            name='TankDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('Normal running', 'Normal running'), ('Low battery', 'Low battery'), ('No signal', 'No signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=1800, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'tank device',
                'verbose_name_plural': 'tank devices',
            },
        ),
        migrations.CreateModel(
            name='TrapView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Mac Address')),
                ('Lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('Long', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('A_TH', models.BooleanField(default=False, verbose_name='Available T y H')),
                ('TimeStart', models.TimeField(blank=True, null=True, verbose_name='On time')),
                ('TimeEnd', models.TimeField(blank=True, null=True, verbose_name='Off time')),
                ('SleepTime', models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time')),
                ('Resolution', models.CharField(blank=True, choices=[('0', 'HD'), ('1', 'FHD')], default='0', max_length=2, null=True, verbose_name='Resolution')),
                ('Objective', models.CharField(blank=True, choices=[('0', 'Plutella Xylostella'), ('1', 'Gorgojo'), ('2', 'Polilla'), ('3', 'Pulga'), ('4', 'Escarabajo'), ('5', 'Mosca de la fruta'), ('6', 'Oruga Zebra'), ('7', 'Oruga Roja')], max_length=2, null=True, verbose_name='Objective')),
                ('runningNN', models.BooleanField(default=False, verbose_name='running NN?')),
            ],
            options={
                'verbose_name': 'TrapView device',
                'verbose_name_plural': 'TrapView devices',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Mac Address')),
                ('A_TH', models.BooleanField(default=False, verbose_name='Available T and H')),
                ('A_WP', models.BooleanField(default=False, verbose_name='Available Wind and pp')),
                ('A_RS', models.BooleanField(default=False, verbose_name='Available Solar Radiation')),
                ('TimeStart', models.TimeField(blank=True, null=True, verbose_name='On time')),
                ('TimeEnd', models.TimeField(blank=True, null=True, verbose_name='Off time')),
                ('SleepTime', models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time')),
            ],
            options={
                'verbose_name': 'Weather station',
                'verbose_name_plural': 'All Weather station',
            },
        ),
        migrations.CreateModel(
            name='WellAnalyzerDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('normal running', 'normal running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=120, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'Well Analyzer device',
                'verbose_name_plural': 'Well Analyzer devices',
            },
        ),
    ]
