# Generated by Django 5.0.6 on 2024-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('normal running', 'normal running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=120, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'tank device',
                'verbose_name_plural': 'tank devices',
            },
        ),
        migrations.CreateModel(
            name='WellAnalyzerDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('normal running', 'normal running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=120, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'Well Analyzer device',
                'verbose_name_plural': 'Well Analyzer devices',
            },
        ),
    ]
