# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdevice',
            name='IdTank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.tank'),
        ),
        migrations.AddField(
            model_name='wellanalyzerdevice',
            name='IdRodPumpWell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.rodpumpwell'),
        ),
    ]
