# Generated by Django 5.0.6 on 2024-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('normal running', 'normal running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=1800, null=True, verbose_name='Sampling Rate')),
            ],
            options={
                'verbose_name': 'Environmental device',
                'verbose_name_plural': 'Environmental devices',
            },
        ),
        migrations.AlterField(
            model_name='tankdevice',
            name='SamplingRate',
            field=models.IntegerField(blank=True, choices=[(1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=1800, null=True, verbose_name='Sampling Rate'),
        ),
    ]
