# Generated by Django 5.0.6 on 2024-06-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_environmentaldevice_alter_tankdevice_samplingrate'),
        ('equipment', '0003_environmental'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaldevice',
            name='IdEnvironmental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.environmental'),
        ),
    ]
