# Generated by Django 5.0.6 on 2025-02-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherstation',
            options={'verbose_name': 'Weather station', 'verbose_name_plural': 'Weather station devices'},
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='TimeEnd',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='TimeStart',
        ),
    ]
