# Generated by Django 4.2.20 on 2025-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_weatherstation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellanalyzerdevice',
            name='RunNNdevice',
            field=models.BooleanField(default=True, verbose_name='NN on devive'),
        ),
        migrations.AddField(
            model_name='wellanalyzerdevice',
            name='RunNNserver',
            field=models.BooleanField(default=False, verbose_name='NN on server'),
        ),
        migrations.AlterField(
            model_name='wellanalyzerdevice',
            name='SamplingRate',
            field=models.IntegerField(blank=True, choices=[(120, '2m'), (300, '5m'), (600, '10m'), (900, '15m'), (1800, '0.5h'), (3600, '1h'), (7200, '2h')], default=120, null=True, verbose_name='Sampling Rate'),
        ),
    ]
