# Generated by Django 5.0.6 on 2024-06-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_environmentaldevice_idenvironmental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdevice',
            name='DeviceStatus',
            field=models.CharField(choices=[('Normal running', 'Normal running'), ('Low battery', 'Low battery'), ('No signal', 'No signal')], default='normal running', max_length=50, verbose_name='Status'),
        ),
    ]
