# Generated by Django 5.0.6 on 2025-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_wellanalyzerdevice_runnndevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='Lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='Long',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
