# Generated by Django 5.0.6 on 2025-06-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_weatherstation_lat_weatherstation_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapview',
            name='isContinue',
            field=models.BooleanField(default=False, verbose_name='is Continue?'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='sensibility',
            field=models.FloatField(default=0.5, verbose_name='sensibilidad'),
        ),
        migrations.AlterField(
            model_name='trapview',
            name='Objective',
            field=models.CharField(blank=True, choices=[('0', 'Plutella Xylostella'), ('1', 'Gorgojo'), ('2', 'Polilla'), ('3', 'Pulga'), ('4', 'Escarabajo'), ('5', 'Mosca de la fruta'), ('6', 'Oruga Zebra'), ('7', 'Oruga Roja'), ('8', 'Mariposas'), ('9', 'Lagartijas'), ('10', 'Sapo')], max_length=2, null=True, verbose_name='Objective'),
        ),
    ]
