# Generated by Django 5.0.6 on 2024-09-12 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_environmentaldevice_owner_tankdevice_owner_and_more'),
        ('equipment', '0014_alter_rodpumpwell_fieldname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamVidDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Device Mac Address')),
                ('DeviceStatus', models.CharField(choices=[('Normal running', 'Normal running'), ('Low battery', 'Low battery'), ('No signal', 'No signal')], default='normal running', max_length=50, verbose_name='Status')),
                ('SamplingRate', models.IntegerField(blank=True, choices=[(30, '0.5h'), (60, '1h'), (120, '2h')], default=60, null=True, verbose_name='Sampling Rate')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('IdEnvironmental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.environmental')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cam video device',
                'verbose_name_plural': 'Cam video devices',
            },
        ),
    ]
