# Generated by Django 5.0.6 on 2024-09-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_camviddevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camviddevice',
            name='img',
        ),
    ]
