# Generated by Django 5.0.6 on 2024-09-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_remove_camviddevice_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camviddevice',
            name='IdEnvironmental',
        ),
    ]
