# Generated by Django 5.0.6 on 2024-09-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_remove_camviddevice_idenvironmental'),
        ('equipment', '0015_visualsamplingpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddevice',
            name='IdVisualSamplingPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.visualsamplingpoint'),
        ),
    ]
