# Generated by Django 5.0.6 on 2024-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_camviddevice_idvisualsamplingpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camviddevice',
            name='DeviceStatus',
        ),
        migrations.RemoveField(
            model_name='camviddevice',
            name='SamplingRate',
        ),
        migrations.AddField(
            model_name='camviddevice',
            name='SleepTime',
            field=models.IntegerField(blank=True, choices=[(30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sampling Rate'),
        ),
        migrations.AddField(
            model_name='camviddevice',
            name='TimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de desactivación'),
        ),
        migrations.AddField(
            model_name='camviddevice',
            name='TimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de activación'),
        ),
        migrations.AddField(
            model_name='camviddevice',
            name='is_continous',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es continuo?'),
        ),
        migrations.AddField(
            model_name='camviddevice',
            name='refresh',
            field=models.IntegerField(blank=True, choices=[(10, '10 s'), (20, '20 s'), (60, '60 s')], default=10, null=True, verbose_name='Sampling Rate'),
        ),
    ]
