# Generated by Django 5.0.6 on 2024-09-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_remove_camviddevice_devicestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camviddevice',
            name='DeviceMacAddress',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='camviddevice',
            name='TimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Off time'),
        ),
        migrations.AlterField(
            model_name='camviddevice',
            name='TimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='On time'),
        ),
        migrations.AlterField(
            model_name='camviddevice',
            name='is_continous',
            field=models.BooleanField(default=False, verbose_name='continuous?'),
        ),
    ]
