# Generated by Django 5.0.6 on 2024-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_alter_camviddevice_devicemacaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camviddevice',
            name='SleepTime',
            field=models.IntegerField(blank=True, choices=[(30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time'),
        ),
    ]
