# Generated by Django 5.0.6 on 2024-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_alter_camviddevice_sleeptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddevice',
            name='saveImage',
            field=models.BooleanField(default=False, verbose_name='save Image?'),
        ),
    ]
