# Generated by Django 4.2.1 on 2024-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_camviddevice_saveimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddevice',
            name='runningNN',
            field=models.BooleanField(default=False, verbose_name='running NN?'),
        ),
    ]
