# Generated by Django 5.0.6 on 2024-11-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_camviddevice_runningnn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Gateway Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Gateway Mac Address')),
                ('TimeStart', models.TimeField(blank=True, null=True, verbose_name='On time')),
                ('TimeEnd', models.TimeField(blank=True, null=True, verbose_name='Off time')),
                ('SleepTime', models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time')),
                ('is_continous', models.BooleanField(default=False, verbose_name='continuous?')),
                ('refresh', models.IntegerField(blank=True, choices=[(10, '10 s'), (20, '20 s'), (60, '60 s')], default=10, null=True, verbose_name='Sampling Rate')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gateway device',
                'verbose_name_plural': 'Gateway devices',
            },
        ),
        migrations.CreateModel(
            name='TrapView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Mac Address')),
                ('A_TH', models.BooleanField(default=False, verbose_name='Available T y H')),
                ('A_WS', models.BooleanField(default=False, verbose_name='Available Weather station')),
                ('IdGateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.gateway')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TrapView device',
                'verbose_name_plural': 'TrapView devices',
            },
        ),
    ]
