# Generated by Django 5.0.6 on 2024-11-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_gateway_trapview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='is_continous',
        ),
    ]
