# Generated by Django 5.0.6 on 2024-11-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_remove_gateway_is_continous'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapview',
            name='runningNN',
            field=models.BooleanField(default=False, verbose_name='running NN?'),
        ),
    ]
