# Generated by Django 5.0.6 on 2024-11-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_trapview_runningnn'),
        ('equipment', '0016_alter_visualsamplingpoint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='IdVisualSamplingPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.visualsamplingpoint'),
        ),
    ]
