# Generated by Django 5.0.6 on 2024-11-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_gateway_idvisualsamplingpoint'),
        ('equipment', '0017_insectmonitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='IdVisualSamplingPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.insectmonitoring'),
        ),
    ]
