# Generated by Django 5.0.6 on 2024-11-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_alter_gateway_idvisualsamplingpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='IdVisualSamplingPoint',
            new_name='IdInsectMonitoring',
        ),
    ]
