# Generated by Django 5.0.6 on 2025-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0023_rename_idvisualsamplingpoint_gateway_idinsectmonitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('DeviceMacAddress', models.CharField(max_length=50, unique=True, verbose_name='Mac Address')),
                ('A_TH', models.BooleanField(default=False, verbose_name='Available T and H')),
                ('A_WP', models.BooleanField(default=False, verbose_name='Available Wind and pp')),
                ('A_RS', models.BooleanField(default=False, verbose_name='Available Solar Radiation')),
            ],
            options={
                'verbose_name': 'Weather station',
                'verbose_name_plural': 'All Weather station',
            },
        ),
        migrations.RemoveField(
            model_name='trapview',
            name='A_WS',
        ),
        migrations.RemoveField(
            model_name='trapview',
            name='Owner',
        ),
    ]
