# Generated by Django 5.0.6 on 2025-01-24 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0024_weatherstation_remove_trapview_a_ws_and_more'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trapview',
            name='IdLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='Objective',
            field=models.CharField(blank=True, choices=[(0, 'Plutella Xylostella'), (1, 'Gorgojo'), (2, 'Polilla'), (3, 'Pulga'), (4, 'Escarabajo'), (5, 'Mosca de la fruta'), (6, 'Oruga Zebra'), (7, 'Origa Roja')], max_length=2, null=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='SleepTime',
            field=models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='TimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Off time'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='TimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='On time'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
