# Generated by Django 5.0.6 on 2025-01-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0025_trapview_idlocation_trapview_objective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='Owner',
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='SleepTime',
            field=models.IntegerField(blank=True, choices=[(2, '2 m'), (5, '5 m'), (30, '30 m'), (60, '1 h'), (120, '2 h')], default=60, null=True, verbose_name='Sleep Time'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='TimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Off time'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='TimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='On time'),
        ),
    ]
