# Generated by Django 5.0.6 on 2025-01-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0026_remove_weatherstation_owner_weatherstation_sleeptime_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='IdInsectMonitoring',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='refresh',
        ),
        migrations.AddField(
            model_name='gateway',
            name='IdLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='IdGateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.gateway'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='IdLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
