# Generated by Django 5.0.6 on 2025-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0027_remove_gateway_idinsectmonitoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapview',
            name='Objective',
            field=models.CharField(blank=True, choices=[(0, 'Plutella Xylostella'), (1, 'Gorgojo'), (2, 'Polilla'), (3, 'Pulga'), (4, 'Escarabajo'), (5, 'Mosca de la fruta'), (6, 'Oruga Zebra'), (7, 'Oruga Roja')], max_length=2, null=True, verbose_name='Objective'),
        ),
    ]
