# Generated by Django 5.0.6 on 2025-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0028_alter_trapview_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapview',
            name='Objective',
            field=models.CharField(blank=True, choices=[('0', 'Plutella Xylostella'), ('1', 'Gorgojo'), ('2', 'Polilla'), ('3', 'Pulga'), ('4', 'Escarabajo'), ('5', 'Mosca de la fruta'), ('6', 'Oruga Zebra'), ('7', 'Oruga Roja')], max_length=2, null=True, verbose_name='Objective'),
        ),
    ]
