# Generated by Django 5.0.6 on 2025-02-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0029_alter_trapview_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapview',
            name='Resolution',
            field=models.IntegerField(blank=True, choices=[('0', 'HD'), ('1', 'FHD')], default='0', null=True, verbose_name='Resolution'),
        ),
    ]
