# Generated by Django 5.0.6 on 2025-02-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0030_trapview_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapview',
            name='Resolution',
            field=models.CharField(blank=True, choices=[('0', 'HD'), ('1', 'FHD')], default='0', max_length=2, null=True, verbose_name='Resolution'),
        ),
    ]
