# Generated by Django 5.0.6 on 2025-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0031_alter_trapview_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapview',
            name='Lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='trapview',
            name='Long',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
