# Generated by Django 5.0.6 on 2026-04-17 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('StationName', models.CharField(max_length=100, unique=True, verbose_name='Station Name')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('HasTemperature', models.BooleanField(default=True, verbose_name='Temperature Sensor')),
                ('HasHumidity', models.BooleanField(default=True, verbose_name='Humidity Sensor')),
                ('HasSolarRadiation', models.BooleanField(default=False, verbose_name='Solar Radiation Sensor')),
                ('HasPrecipitation', models.BooleanField(default=False, verbose_name='Precipitation Sensor')),
                ('HasWind', models.BooleanField(default=False, verbose_name='Wind Sensor')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Out of service', 'Out of service')], default='Active', max_length=50, verbose_name='Status')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Station',
                'verbose_name_plural': 'Weather Stations',
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(verbose_name='Date / Time')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('SolarRadiation', models.FloatField(blank=True, null=True, verbose_name='Solar Radiation (W/m²)')),
                ('Precipitation', models.FloatField(blank=True, null=True, verbose_name='Precipitation (mm)')),
                ('WindSpeed', models.FloatField(blank=True, null=True, verbose_name='Wind Speed (m/s)')),
                ('WindDirection', models.FloatField(blank=True, null=True, verbose_name='Wind Direction (°)')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weatherStation.weatherstation')),
            ],
            options={
                'verbose_name': 'Weather Reading',
                'verbose_name_plural': 'Weather Readings',
                'ordering': ['-DateCreate'],
            },
        ),
    ]
