# Generated by Django 5.0.6 on 2026-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='MacAddress',
            field=models.CharField(blank=True, help_text='e.g. AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='TimeSleep',
            field=models.CharField(choices=[('5m', 'Every 5 minutes'), ('30m', 'Every 30 minutes'), ('1h', 'Every 1 hour')], default='30m', max_length=3, verbose_name='Reading Interval'),
        ),
    ]
