# Generated by Django 5.0.6 on 2026-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherStation', '0002_weatherstation_macaddress_weatherstation_timesleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='HasHumidity',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='HasTemperature',
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='HasTempHumidity',
            field=models.BooleanField(default=True, verbose_name='Temperature & Humidity Sensor'),
        ),
    ]
