# Generated by Django 5.0.6 on 2026-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherStation', '0003_remove_weatherstation_hashumidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='VoltageBattery',
            field=models.FloatField(blank=True, null=True, verbose_name='Battery Voltage (V)'),
        ),
    ]
