# Generated by Django 5.0.6 on 2026-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherStation', '0004_weatherreading_voltagebattery'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='LocalTimestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Device Timestamp'),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='TypeConn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Connection Type'),
        ),
        migrations.AlterField(
            model_name='weatherreading',
            name='DateCreate',
            field=models.DateTimeField(verbose_name='Server Timestamp'),
        ),
    ]
