# Generated by Django 4.2.1 on 2023-08-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('OilProd', models.FloatField(blank=True, null=True, verbose_name='Oil Production')),
                ('WaterProd', models.FloatField(blank=True, null=True, verbose_name='Water Production')),
                ('PumpName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
                ('UserAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'All production',
            },
        ),
    ]
