# Generated by Django 4.2.1 on 2023-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionfluid',
            name='DateTest',
            field=models.DateField(blank=True, null=True),
        ),
    ]
