# Generated by Django 5.0.6 on 2026-08-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OILFIELD', '0005_alter_well_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TankStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('MacAddress', models.CharField(help_text='Identificador del dispositivo, ej. AA:BB:CC:DD:EE:FF', max_length=17, unique=True, verbose_name='MAC Address')),
                ('SensorType', models.CharField(choices=[('ultrasonic', 'Ultrasónico'), ('radar', 'Radar'), ('pressure', 'Presión diferencial'), ('float', 'Flotador'), ('manual', 'Manual')], default='ultrasonic', max_length=20, verbose_name='Tipo de sensor')),
                ('SamplingRate', models.IntegerField(choices=[(900, '15 min'), (1800, '30 min'), (3600, '1 hora'), (7200, '2 horas')], default=1800, verbose_name='Intervalo de muestreo (s)')),
                ('Status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento'), ('fault', 'Falla')], default='active', max_length=20, verbose_name='Estado')),
                ('LastSeen', models.DateTimeField(blank=True, null=True, verbose_name='Última conexión')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltaje batería (V)')),
                ('MqttBroker', models.CharField(blank=True, max_length=200, null=True, verbose_name='Broker MQTT')),
                ('MqttPort', models.PositiveIntegerField(default=1883, verbose_name='Puerto MQTT')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_stations', to=settings.AUTH_USER_MODEL)),
                ('Tank', models.ForeignKey(blank=True, help_text='Tanque de la infraestructura al que está instalado este sensor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_stations', to='OILFIELD.tank', verbose_name='Tanque monitorado')),
            ],
            options={
                'verbose_name': 'Estación de Tanque',
                'verbose_name_plural': 'Estaciones de Tanque',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='TankIoTReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(verbose_name='Timestamp servidor')),
                ('LocalTimestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp dispositivo')),
                ('TypeConn', models.CharField(blank=True, choices=[('WIFI', 'WiFi'), ('LTE', 'LTE/4G'), ('GPRS', 'GPRS'), ('RS485', 'RS-485')], max_length=10, null=True, verbose_name='Conexión')),
                ('Level', models.FloatField(blank=True, null=True, verbose_name='Nivel (cm)')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('WaterLevel', models.FloatField(blank=True, null=True, verbose_name='Nivel agua (cm)')),
                ('Volume', models.FloatField(blank=True, null=True, verbose_name='Volumen (bbl)')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Batería (V)')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='oilfield_tank.tankstation')),
            ],
            options={
                'verbose_name': 'Lectura IoT de Tanque',
                'verbose_name_plural': 'Lecturas IoT de Tanque',
                'ordering': ['-DateCreate'],
                'indexes': [models.Index(fields=['Station', 'DateCreate'], name='oilfield_ta_Station_7a5c9f_idx')],
            },
        ),
    ]
