# Generated by Django 5.0.6 on 2026-08-25 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OILFIELD', '0005_alter_well_status'),
        ('oilfield_tank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tankiotreading',
            options={'ordering': ['-ReadingDate'], 'verbose_name': 'Lectura de Tanque', 'verbose_name_plural': 'Lecturas de Tanque'},
        ),
        migrations.RemoveIndex(
            model_name='tankiotreading',
            name='oilfield_ta_Station_7a5c9f_idx',
        ),
        migrations.AddField(
            model_name='tankiotreading',
            name='EnteredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_iot_readings_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tankiotreading',
            name='Notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='tankiotreading',
            name='ReadingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora lectura'),
        ),
        migrations.AddField(
            model_name='tankiotreading',
            name='Source',
            field=models.CharField(choices=[('iot', 'IoT'), ('manual', 'Manual'), ('scada', 'SCADA')], default='iot', max_length=10, verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='tankiotreading',
            name='Tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot_readings', to='OILFIELD.tank', verbose_name='Tanque'),
        ),
        migrations.AlterField(
            model_name='tankiotreading',
            name='DateCreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp servidor'),
        ),
        migrations.AlterField(
            model_name='tankiotreading',
            name='Station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='oilfield_tank.tankstation'),
        ),
        migrations.AddIndex(
            model_name='tankiotreading',
            index=models.Index(fields=['Station', 'ReadingDate'], name='oilfield_ta_Station_0066a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tankiotreading',
            index=models.Index(fields=['Tank', 'ReadingDate'], name='oilfield_ta_Tank_id_98928f_idx'),
        ),
    ]
