# Generated by Django 4.2.1 on 2025-02-07 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('EnvironmentalName', models.CharField(max_length=100, unique=True, verbose_name='Environmental Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environmental sesnors',
            },
        ),
        migrations.CreateModel(
            name='InsectMonitoring',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Visual Sanple Point Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Insect monitoring',
                'verbose_name_plural': 'Insect monitoring Points',
            },
        ),
        migrations.CreateModel(
            name='RodPumpWell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('WellName', models.CharField(max_length=50, unique=True, verbose_name='Well Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('InstallationDate', models.DateField()),
                ('InstallationComment', models.TextField(max_length=500, verbose_name='Installation Comment')),
                ('PumpIntake', models.FloatField(blank=True, null=True, verbose_name='Pump Intake')),
                ('MeasuredDepth', models.FloatField(blank=True, null=True, verbose_name='Measured Depth')),
                ('PlungerDiameter', models.FloatField(blank=True, null=True, verbose_name='Plunger Diameter')),
                ('TrueVerticalDepth', models.FloatField(blank=True, null=True, verbose_name='True Vertical Depth')),
                ('TotalRodLength', models.FloatField(blank=True, null=True, verbose_name='Total Rod Length')),
                ('TotalRodWeight', models.FloatField(blank=True, null=True, verbose_name='Total Rod Weight')),
                ('StrokeLength', models.FloatField(blank=True, null=True, verbose_name='Stroke Length')),
                ('EngineType', models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas')], default='Gas', max_length=50, verbose_name='Engine Type')),
                ('PolishedRodDiameter', models.FloatField(blank=True, null=True, verbose_name='Polished Rod Diameter')),
                ('EngineBrand', models.CharField(max_length=50, verbose_name='Engine Brand')),
                ('ProdTime', models.FloatField(blank=True, null=True, verbose_name='Production Time')),
                ('RestTime', models.FloatField(blank=True, null=True, verbose_name='Rest Time')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Mormal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='Normal running', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Rod Pump Well',
                'verbose_name_plural': 'Rod Pump Wells',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TankName', models.CharField(max_length=100, unique=True, verbose_name='Tank Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('TankHeight', models.FloatField(blank=True, null=True, verbose_name='Tank Height')),
                ('TankFactor', models.FloatField(blank=True, null=True, verbose_name='Tank Factor')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='Normal running', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
            },
        ),
        migrations.CreateModel(
            name='VisualSamplingPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('VisualSamplingPointName', models.CharField(max_length=100, unique=True, verbose_name='Visual Sanple Point Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'verbose_name': 'Visual Sampling',
                'verbose_name_plural': 'Visual Sampling Points',
            },
        ),
    ]
