# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0001_initial'),
        ('field', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('TankName', models.CharField(max_length=100, unique=True, verbose_name='Tank Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('TankHeight', models.FloatField(blank=True, null=True, verbose_name='Tank Height')),
                ('TankFactor', models.FloatField(blank=True, null=True, verbose_name='Tank Factor')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'tank',
                'verbose_name_plural': 'tanks',
            },
        ),
        migrations.CreateModel(
            name='RodPumpWell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('WellName', models.CharField(max_length=50, unique=True, verbose_name='Well Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('InstallationDate', models.DateField()),
                ('InstallationComment', models.TextField(max_length=500, verbose_name='Installation Comment')),
                ('PumpIntake', models.FloatField(blank=True, null=True, verbose_name='Pump Intake')),
                ('MeasuredDepth', models.FloatField(blank=True, null=True, verbose_name='Measured Depth')),
                ('PlungerDiameter', models.FloatField(blank=True, null=True, verbose_name='Plunger Diameter')),
                ('TrueVerticalDepth', models.FloatField(blank=True, null=True, verbose_name='True Vertical Depth')),
                ('TotalRodLength', models.FloatField(blank=True, null=True, verbose_name='Total Rod Length')),
                ('TotalRodWeight', models.FloatField(blank=True, null=True, verbose_name='Total Rod Weight')),
                ('StrokeLength', models.FloatField(blank=True, null=True, verbose_name='Stroke Length')),
                ('EngineType', models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas')], default='Gas', max_length=50, verbose_name='Engine Type')),
                ('PolishedRodDiameter', models.FloatField(blank=True, null=True, verbose_name='Polished Rod Diameter')),
                ('EngineBrand', models.CharField(max_length=50, verbose_name='Engine Brand')),
                ('ProdTime', models.FloatField(blank=True, null=True, verbose_name='Production Time')),
                ('RestTime', models.FloatField(blank=True, null=True, verbose_name='Rest Time')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Mormal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='Normal running', max_length=50, verbose_name='Status')),
                ('BatteryName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery')),
                ('FieldName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'verbose_name': 'Rod Pump Well',
                'verbose_name_plural': 'Rod Pump Wells',
            },
        ),
    ]
