# Generated by Django 4.2.1 on 2025-02-07 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0001_initial'),
        ('groups', '0001_initial'),
        ('equipment', '0001_initial'),
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visualsamplingpoint',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cam_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualsamplingpoint',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='BatteryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery'),
        ),
        migrations.AddField(
            model_name='tank',
            name='FieldName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
        migrations.AddField(
            model_name='tank',
            name='GroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='tank',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tank_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='WellsAssigned',
            field=models.ManyToManyField(to='equipment.rodpumpwell'),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='BatteryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery'),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='FieldName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='GroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RP_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insectmonitoring',
            name='GroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='insectmonitoring',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insect_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insectmonitoring',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmental',
            name='GroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='environmental',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Env_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmental',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
