# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0001_initial'),
        ('equipment', '0001_initial'),
        ('field', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rodpumpwell',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='BatteryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery'),
        ),
        migrations.AddField(
            model_name='tank',
            name='FieldName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
        migrations.AddField(
            model_name='tank',
            name='GroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='tank',
            name='SupervisorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='WellsAssigned',
            field=models.ManyToManyField(related_name='WellsAssigned', to='equipment.rodpumpwell'),
        ),
    ]
