# Generated by Django 5.0.6 on 2024-06-21 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
        ('equipment', '0002_initial'),
        ('field', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('EnvironmentalName', models.CharField(max_length=100, unique=True, verbose_name='Environmental Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
                ('BatteryName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery')),
                ('FieldName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('SupervisorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environmental sesnors',
            },
        ),
    ]
