# Generated by Django 4.2.20 on 2025-04-05 18:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='environmental',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='environmental',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='environmental',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='environmental',
            name='Status',
            field=models.CharField(choices=[('0', 'Out of service'), ('1', 'Normal running'), ('2', 'Maintenance')], default='1', max_length=50, verbose_name='Status'),
        ),
    ]
