# Generated by Django 5.0.6 on 2024-06-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_environmental'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental',
            name='FieldName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
    ]
