# Generated by Django 5.0.6 on 2025-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_environmental_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmental',
            options={'verbose_name': 'Environment', 'verbose_name_plural': 'Environmental sensors'},
        ),
    ]
