# Generated by Django 5.0.6 on 2024-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_environmental_fieldname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'verbose_name': 'Tank', 'verbose_name_plural': 'Tanks'},
        ),
        migrations.AlterField(
            model_name='tank',
            name='Status',
            field=models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='Normal running', max_length=50, verbose_name='Status'),
        ),
    ]
