# Generated by Django 5.0.6 on 2024-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_tank_created_tank_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='WellsAssigned',
            field=models.ManyToManyField(to='equipment.rodpumpwell'),
        ),
    ]
