# Generated by Django 5.0.6 on 2024-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_tank_wellsassigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='DateCreate',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
