# Generated by Django 5.0.6 on 2024-06-22 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_tank_created_at_remove_tank_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
