# Generated by Django 5.0.6 on 2024-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_tank_created_at_tank_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmental',
            old_name='DateCreate',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='environmental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
