# Generated by Django 5.0.6 on 2024-06-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_rename_datecreate_environmental_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental',
            name='BatteryName',
        ),
        migrations.RemoveField(
            model_name='environmental',
            name='FieldName',
        ),
    ]
