# Generated by Django 5.0.6 on 2024-06-23 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_remove_environmental_batteryname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='environmental',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Env_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodpumpwell',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RP_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tank',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tank_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
