# Generated by Django 5.0.6 on 2024-06-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_environmental_owner_rodpumpwell_owner_tank_owner'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpwell',
            name='FieldName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
    ]
