# Generated by Django 5.0.6 on 2024-09-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_rodpumpwell_fieldname'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualSamplingPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('VisualSamplingPointName', models.CharField(max_length=100, unique=True, verbose_name='Visual Sanple Point Name')),
                ('LatLocation', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LonLocation', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Status', models.CharField(choices=[('Out of service', 'Out of service'), ('Maintenance', 'Maintenance'), ('Normal running', 'Normal running'), ('Testing', 'Testing'), ('Not assigned', 'Not assigned')], default='normal running', max_length=50, verbose_name='Status')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cam_owner', to=settings.AUTH_USER_MODEL)),
                ('SupervisorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VisualSampling',
                'verbose_name_plural': 'VisualSampling sensors',
            },
        ),
    ]
