# Generated by Django 5.0.6 on 2024-09-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_visualsamplingpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualsamplingpoint',
            options={'verbose_name': 'Visual Sampling', 'verbose_name_plural': 'Visual Sampling Points'},
        ),
    ]
