# Generated by Django 5.0.6 on 2026-08-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OILFIELD', '0005_alter_well_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellAnalyzerStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('MacAddress', models.CharField(help_text='Identificador del dispositivo, ej. AA:BB:CC:DD:EE:FF', max_length=17, unique=True, verbose_name='MAC Address')),
                ('SamplingRate', models.IntegerField(choices=[(300, '5 min'), (900, '15 min'), (1800, '30 min'), (3600, '1 hora')], default=1800, verbose_name='Intervalo de muestreo (s)')),
                ('Status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento'), ('fault', 'Falla')], default='active', max_length=20, verbose_name='Estado')),
                ('OperationalStatus', models.CharField(blank=True, choices=[('producing', 'Produciendo'), ('pump_off', 'Pump Off'), ('gas_lock', 'Gas Lock'), ('fluid_pound', 'Fluid Pound'), ('low_fillage', 'Bajo Llenado'), ('overloaded', 'Sobrecarga'), ('maintenance', 'Mantenimiento'), ('stopped', 'Detenido'), ('fault_mech', 'Falla Mecánica'), ('inactive', 'Inactivo')], default='inactive', max_length=20, verbose_name='Estado operacional')),
                ('LastSeen', models.DateTimeField(blank=True, null=True, verbose_name='Última conexión')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltaje batería (V)')),
                ('MqttBroker', models.CharField(blank=True, max_length=200, null=True, verbose_name='Broker MQTT')),
                ('MqttPort', models.PositiveIntegerField(default=1883, verbose_name='Puerto MQTT')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_analyzer_stations', to=settings.AUTH_USER_MODEL)),
                ('Well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzer_stations', to='OILFIELD.well', verbose_name='Pozo monitorado')),
            ],
            options={
                'verbose_name': 'Analizador de Pozo',
                'verbose_name_plural': 'Analizadores de Pozo',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyzerReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(verbose_name='Timestamp servidor')),
                ('LocalTimestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp dispositivo')),
                ('TypeConn', models.CharField(blank=True, choices=[('WIFI', 'WiFi'), ('LTE', 'LTE/4G'), ('GPRS', 'GPRS'), ('RS485', 'RS-485')], max_length=10, null=True, verbose_name='Conexión')),
                ('SPM', models.FloatField(blank=True, null=True, verbose_name='SPM')),
                ('Fillage', models.FloatField(blank=True, null=True, verbose_name='Fillage (%)')),
                ('RunTime', models.FloatField(blank=True, null=True, verbose_name='Run Time (h)')),
                ('OilProduction', models.FloatField(blank=True, null=True, verbose_name='Prod. Petróleo (bbl/d)')),
                ('WaterProduction', models.FloatField(blank=True, null=True, verbose_name='Prod. Agua (bbl/d)')),
                ('Torque', models.FloatField(blank=True, null=True, verbose_name='Torque (ft-lb)')),
                ('MotorCurrent', models.FloatField(blank=True, null=True, verbose_name='Corriente (A)')),
                ('Vibration', models.FloatField(blank=True, null=True, verbose_name='Vibración (mm/s)')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('DynamicLevel', models.FloatField(blank=True, null=True, verbose_name='Nivel dinámico (m)')),
                ('VolumetricEfficiency', models.FloatField(blank=True, null=True, verbose_name='Efic. volumétrica (%)')),
                ('OperationalStatus', models.CharField(blank=True, choices=[('producing', 'Produciendo'), ('pump_off', 'Pump Off'), ('gas_lock', 'Gas Lock'), ('fluid_pound', 'Fluid Pound'), ('low_fillage', 'Bajo Llenado'), ('overloaded', 'Sobrecarga'), ('maintenance', 'Mantenimiento'), ('stopped', 'Detenido'), ('fault_mech', 'Falla Mecánica'), ('inactive', 'Inactivo')], default='producing', max_length=20, verbose_name='Estado operacional')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Batería (V)')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='oilfield_wellanalyzer.wellanalyzerstation')),
            ],
            options={
                'verbose_name': 'Lectura Dinamométrica',
                'verbose_name_plural': 'Lecturas Dinamométricas',
                'ordering': ['-DateCreate'],
                'indexes': [models.Index(fields=['Station', 'DateCreate'], name='oilfield_we_Station_3ddf00_idx')],
            },
        ),
    ]
