# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('GroupName', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Group Name')),
                ('Company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
