# Generated by Django 5.0.6 on 2025-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre')),
                ('LastName', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Apellido')),
                ('Email', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Correo')),
                ('Organization', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Organización')),
                ('Interes', models.CharField(blank=True, choices=[('0', 'Monitoreo de fauna'), ('1', 'Monitoreo de plagas'), ('2', 'Industria'), ('3', 'Otros')], max_length=1100, null=True, verbose_name='Interés')),
                ('Message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto de interés',
                'verbose_name_plural': 'Todos los contactos de interés',
            },
        ),
    ]
