# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('UserName', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('Role', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Worker', 'Worker')], default='Worker', max_length=10, verbose_name='Role')),
                ('CompanyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='company.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
