# Generated by Django 5.0.6 on 2026-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(choices=[('transformadores', 'Transformadores'), ('fauna', 'Fauna'), ('oilfield', 'Oilfield')], max_length=50, unique=True, verbose_name='Código')),
                ('Name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Description', models.TextField(blank=True, verbose_name='Descripción')),
                ('Icon', models.CharField(blank=True, default='fas fa-th', max_length=60, verbose_name='Ícono FA')),
                ('DashboardUrl', models.CharField(blank=True, max_length=100, verbose_name='URL Dashboard')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador'), ('operator', 'Operador')], default='operator', max_length=10, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='Applications',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.application', verbose_name='Aplicaciones habilitadas'),
        ),
    ]
