# Generated by Django 5.0.6 on 2026-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_seguridad_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Code',
            field=models.CharField(choices=[('transformadores', 'Transformadores'), ('fauna', 'Fauna'), ('oilfield', 'Oilfield'), ('seguridad', 'Seguridad')], max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
