# Generated by Django 4.2.1 on 2023-09-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('FieldName', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Field Name')),
                ('LocationState', models.CharField(max_length=100, verbose_name='Location State')),
                ('LocationCounty', models.CharField(max_length=100, verbose_name='Location County')),
                ('Company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
