# Generated by Django 4.2.1 on 2023-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('CompanyName', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('LocationState', models.CharField(max_length=100, verbose_name='Location State')),
                ('LocationCounty', models.CharField(max_length=100, verbose_name='Location County')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
