# Generated by Django 5.0.6 on 2024-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('LocationState', models.CharField(max_length=100, verbose_name='Location State')),
                ('LocationCounty', models.CharField(max_length=100, verbose_name='Location County')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
