# Generated by Django 5.0.6 on 2025-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CompanyType',
            field=models.CharField(blank=True, choices=[('0', 'Oil Production'), ('1', 'Agricultural'), ('9', 'Other')], default='9', max_length=2, null=True, verbose_name='Role'),
        ),
    ]
