# Generated by Django 4.2.20 on 2025-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_companytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyType',
            field=models.CharField(blank=True, choices=[('0', 'Oil Production'), ('1', 'Agricultural'), ('9', 'Other')], default='9', max_length=2, null=True, verbose_name='Company Type'),
        ),
    ]
