# Generated by Django 5.0.6 on 2026-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='company',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
    ]
