# Generated by Django 4.2.1 on 2023-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DeviceName', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Device Name')),
                ('Available', models.BooleanField(choices=[(True, 'available'), (False, 'not available')], default=True, verbose_name='Available')),
                ('MacAddress', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mac Address')),
                ('IpAddress', models.CharField(max_length=100, unique=True, verbose_name='Ip Address')),
                ('Status', models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='stopped', max_length=50, verbose_name='Status')),
                ('TimeOn', models.FloatField(blank=True, null=True, verbose_name='Time On')),
                ('TimeOff', models.FloatField(blank=True, null=True, verbose_name='Time Off')),
                ('ThresholdAlert1', models.FloatField(blank=True, null=True, verbose_name='Threshold Alert 1')),
                ('ThresholdAlert2', models.FloatField(blank=True, null=True, verbose_name='Threshold Alert 2')),
                ('ThresholdStop', models.FloatField(blank=True, null=True, verbose_name='Threshold Stop')),
                ('Refresh', models.FloatField(blank=True, choices=[(30, '30s'), (60, '1m'), (120, '2m'), (300, '5m'), (600, '10m'), (900, '15m'), (1800, '30m')], default=120, null=True, verbose_name='Refresh')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'all settings',
            },
        ),
    ]
