# Generated by Django 4.2.1 on 2023-08-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Available', models.BooleanField(default=True, verbose_name='Available')),
                ('IpAddress', models.CharField(max_length=100, unique=True, verbose_name='Ip Address')),
                ('Refresh', models.FloatField(blank=True, null=True, verbose_name='Refresh Time')),
                ('PumpName', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
    ]
