# Generated by Django 4.2.1 on 2023-09-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0002_well_motortype_well_plungerdiameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Available', models.BooleanField(choices=[('available', True), ('not available', False)], default=True, verbose_name='Available')),
                ('MacAddress', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mac Address')),
                ('IpAddress', models.CharField(max_length=100, unique=True, verbose_name='Ip Address')),
                ('RefreshTime', models.FloatField(blank=True, null=True, verbose_name='Refresh Time')),
                ('Status', models.CharField(choices=[('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal')], default='running', max_length=50, verbose_name='Status')),
                ('TimeOn', models.FloatField(blank=True, null=True, verbose_name='Time On')),
                ('TimeOff', models.FloatField(blank=True, null=True, verbose_name='Time Off')),
                ('ThresholdAlert1', models.FloatField(blank=True, null=True, verbose_name='Threshold Alert 1')),
                ('ThresholdAlert2', models.FloatField(blank=True, null=True, verbose_name='Threshold Alert 2')),
                ('ThresholdStop', models.FloatField(blank=True, null=True, verbose_name='Threshold Stop')),
                ('PumpName', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'all settings',
            },
        ),
    ]
