# Generated by Django 4.2.1 on 2023-09-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='RefreshTime',
        ),
        migrations.AddField(
            model_name='setting',
            name='Refresh',
            field=models.FloatField(blank=True, null=True, verbose_name='Refresh'),
        ),
    ]
