# Generated by Django 4.2.1 on 2023-09-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='PumpName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well'),
        ),
    ]
