# Generated by Django 4.2.1 on 2024-01-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='Refresh',
        ),
        migrations.AddField(
            model_name='setting',
            name='DeviceType',
            field=models.CharField(choices=[('Rod Pump Analyzer', 'Rod Pump Analyzer'), ('Tank Level Meter', 'Tank Level Meter')], default='Rod Pump Analyzer', max_length=50, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='setting',
            name='PumpName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well'),
        ),
        migrations.AddField(
            model_name='setting',
            name='TankFactor',
            field=models.FloatField(blank=True, null=True, verbose_name='Tank Factor'),
        ),
        migrations.AddField(
            model_name='setting',
            name='TankHeight',
            field=models.FloatField(blank=True, null=True, verbose_name='Tank Height'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='Status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal'), ('not synchronized', 'not synchronized')], default='stopped', max_length=50, verbose_name='Status'),
        ),
    ]
