# Generated by Django 4.2.1 on 2023-10-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='TankFactor',
            field=models.FloatField(blank=True, null=True, verbose_name='Tank Factor'),
        ),
        migrations.AddField(
            model_name='setting',
            name='TankHeight',
            field=models.FloatField(blank=True, null=True, verbose_name='Tank Height'),
        ),
    ]
