# Generated by Django 4.2.1 on 2023-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_setting_available_alter_setting_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='DeviceName',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Device Name'),
        ),
    ]
