# Generated by Django 4.2.1 on 2023-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_setting_pumpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='Status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal'), ('not synchronized', 'not synchronized')], default='stopped', max_length=50, verbose_name='Status'),
        ),
    ]
