# Generated by Django 4.2.1 on 2023-10-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_setting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='Refresh',
        ),
    ]
