# Generated by Django 5.0.6 on 2026-04-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('StationName', models.CharField(max_length=100, unique=True, verbose_name='Station Name')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Out of service', 'Out of service')], default='Active', max_length=50, verbose_name='Status')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Station',
                'verbose_name_plural': 'Camera Stations',
            },
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCapture', models.DateTimeField(verbose_name='Capture Date / Time')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='camera_captures/%Y/%m/', verbose_name='Capture Image')),
                ('Species', models.CharField(max_length=200, verbose_name='Species')),
                ('SpeciesCount', models.PositiveIntegerField(default=1, verbose_name='Individual Count')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Battery Voltage (V)')),
                ('Notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='camera.camerastation')),
            ],
            options={
                'verbose_name': 'Camera Capture',
                'verbose_name_plural': 'Camera Captures',
                'ordering': ['-DateCapture'],
            },
        ),
    ]
