# Generated by Django 5.0.6 on 2026-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerastation',
            name='HasTempHumidity',
            field=models.BooleanField(default=True, verbose_name='Temperature & Humidity Sensor'),
        ),
    ]
