# Generated by Django 5.0.6 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camerastation_hastemphumidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerastation',
            name='MacAddress',
            field=models.CharField(blank=True, help_text='e.g. AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='MAC Address'),
        ),
    ]
