# Generated by Django 5.0.6 on 2026-05-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_camerastation_timesleepc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerastation',
            name='TurnOffTime',
            field=models.TimeField(default='17:00', verbose_name='Turn Off Time'),
        ),
        migrations.AlterField(
            model_name='camerastation',
            name='TurnOnTime',
            field=models.TimeField(default='10:00', verbose_name='Turn On Time'),
        ),
        migrations.AlterField(
            model_name='capturedetection',
            name='Capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='camera.cameracapture'),
        ),
        migrations.AlterField(
            model_name='capturedetection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specieslabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
