# Generated by Django 5.0.6 on 2026-05-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_alter_camerastation_turnofftime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDeviceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRecord', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Battery (V)')),
                ('MemFree', models.FloatField(blank=True, null=True, verbose_name='Free Memory (KB)')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='camera.camerastation')),
            ],
            options={
                'verbose_name': 'Device Health Log',
                'verbose_name_plural': 'Device Health Logs',
                'ordering': ['-DateRecord'],
            },
        ),
    ]
