# Generated by Django 5.0.6 on 2026-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_cameradevicehealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameracapture',
            name='MemFree',
            field=models.FloatField(blank=True, null=True, verbose_name='Free Memory (KB)'),
        ),
    ]
