# Generated by Django 4.2.1 on 2025-02-07 20:46

import django.contrib.postgres.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamVidData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('VoltagePanel', models.FloatField(blank=True, null=True, verbose_name='Voltage Panel')),
                ('WindVelocity', models.FloatField(blank=True, null=True, verbose_name='Wind Velocity')),
                ('WindDirection', models.FloatField(blank=True, null=True, verbose_name='Wind Direction')),
                ('RainCounter', models.IntegerField(blank=True, null=True, verbose_name='Rain Counter')),
                ('Classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(0, 'Mariposa 1'), (1, 'Mariposa 2'), (2, 'Mariposa 3'), (3, 'Mariposa 4')], max_length=3, null=True, verbose_name='Class'), blank=True, null=True, size=None)),
                ('Quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('nDetected', models.IntegerField(blank=True, null=True, verbose_name='N Detected')),
                ('img64', models.TextField(blank=True, null=True, verbose_name='img64')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('img_file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Path')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Camera Data',
                'verbose_name_plural': 'All Camera Data',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity1', models.FloatField(blank=True, null=True, verbose_name='Humidity 1')),
                ('Temperature1', models.FloatField(blank=True, null=True, verbose_name='Temperature 1')),
                ('AtmosphericPressure1', models.FloatField(blank=True, null=True, verbose_name='Atmospheric Pressure 1')),
                ('Humidity2', models.FloatField(blank=True, null=True, verbose_name='Humidity 2')),
                ('Temperature2', models.FloatField(blank=True, null=True, verbose_name='Temperature 2')),
                ('AtmosphericPressure2', models.FloatField(blank=True, null=True, verbose_name='Atmospheric Pressure 2')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Environmental Data',
                'verbose_name_plural': 'All Environmental Data',
            },
        ),
        migrations.CreateModel(
            name='GatewayData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('Status', models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=20, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Gateway Data',
                'verbose_name_plural': 'All Gateway Data',
            },
        ),
        migrations.CreateModel(
            name='RodPumpData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('RawSurfaceLoad', models.TextField(blank=True, null=True, verbose_name='Raw Surf Load')),
                ('RawSurfacePosition', models.TextField(blank=True, null=True, verbose_name='Raw Surf Position')),
                ('SurfaceLoad', models.TextField(blank=True, null=True, verbose_name='Surf Load')),
                ('SurfacePosition', models.TextField(blank=True, null=True, verbose_name='Surf Position')),
                ('DownLoad', models.TextField(blank=True, null=True, verbose_name='Down Load')),
                ('DownPosition', models.TextField(blank=True, null=True, verbose_name='Down Position')),
                ('RawAcceleration', models.TextField(blank=True, null=True, verbose_name='RawAcceleration')),
                ('RunTime', models.FloatField(blank=True, null=True, verbose_name='Run Time')),
                ('SPM', models.FloatField(blank=True, null=True, verbose_name='SPM')),
                ('Production', models.FloatField(blank=True, null=True, verbose_name='Production')),
                ('PumpFillage', models.FloatField(blank=True, null=True, verbose_name='Pump Fillage')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped unit', 'Stopped unit')], max_length=100, null=True, verbose_name='Status')),
                ('Diagnosis', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('None', 'None'), ('Full pump', 'Full pump'), ('Leak travel valve', 'Leak travel valve'), ('Leak standing valve', 'Leak standing valve'), ('Worn pump barrel', 'Worn pump barrel'), ('Light fluid stroke', 'Light fluid stroke'), ('Medium fluid stroke', 'Medium fluid stroke'), ('Severe fluid stroke', 'Severe fluid stroke'), ('Gas interference', 'Gas interference'), ('Shock of pump up', 'Shock of pump up'), ('Shock of pump down', 'Shock of pump down'), ('Recovering level', 'Recovering level'), ('Rods broken', 'Rods broken')], max_length=100, null=True, verbose_name='Diagnosis')),
                ('Recomendation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Good work area', 'Good work area'), ('Schedule to workover', 'Schedule to workover'), ('Unit re-spacing', 'Unit re-spacing'), ('Reduce strokes per minute', 'Reduce strokes per minute'), ('Stop pump unit', 'Stop pump unit')], max_length=100, null=True, verbose_name='Recomendation')),
            ],
            options={
                'verbose_name': 'Socker Rod Pump Data',
                'verbose_name_plural': 'All Socker Rod Pump Data',
            },
        ),
        migrations.CreateModel(
            name='TankData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Level', models.FloatField(blank=True, null=True, verbose_name='Oil Level')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tank Data',
                'verbose_name_plural': 'All Tank Data',
            },
        ),
        migrations.CreateModel(
            name='TrapViewData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('Objective', models.CharField(blank=True, null=True, verbose_name='Plaga')),
                ('nDetected', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('img64', models.TextField(blank=True, null=True, verbose_name='img64')),
                ('img_bool', models.BooleanField(default=False, verbose_name='image?')),
                ('Status', models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=2, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Trap View Data',
                'verbose_name_plural': 'All Trap View Data',
            },
        ),
        migrations.CreateModel(
            name='WeatherStationData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('WindVelocity', models.FloatField(blank=True, null=True, verbose_name='Wind Velocity')),
                ('WindDirection', models.FloatField(blank=True, null=True, verbose_name='Wind Direction')),
                ('RainCounter', models.IntegerField(blank=True, null=True, verbose_name='Rain Counter')),
                ('Radiation', models.IntegerField(blank=True, null=True, verbose_name='Solar Radiation')),
                ('Status', models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=20, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Weather Station Data',
                'verbose_name_plural': 'All Weather Station Data',
            },
        ),
    ]
