# Generated by Django 5.0.6 on 2024-06-16 22:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RodPumpData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('RawSurfaceLoad', models.TextField(blank=True, null=True, verbose_name='Raw Surf Load')),
                ('RawSurfacePosition', models.TextField(blank=True, null=True, verbose_name='Raw Surf Position')),
                ('SurfaceLoad', models.TextField(blank=True, null=True, verbose_name='Surf Load')),
                ('SurfacePosition', models.TextField(blank=True, null=True, verbose_name='Surf Position')),
                ('DownLoad', models.TextField(blank=True, null=True, verbose_name='Down Load')),
                ('DownPosition', models.TextField(blank=True, null=True, verbose_name='Down Position')),
                ('RawAcceleration', models.TextField(blank=True, null=True, verbose_name='RawAcceleration')),
                ('RunTime', models.FloatField(blank=True, null=True, verbose_name='Run Time')),
                ('SPM', models.FloatField(blank=True, null=True, verbose_name='SPM')),
                ('Production', models.FloatField(blank=True, null=True, verbose_name='Production')),
                ('PumpFillage', models.FloatField(blank=True, null=True, verbose_name='Pump Fillage')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped unit', 'Stopped unit')], max_length=100, null=True, verbose_name='Status')),
                ('Diagnosis', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('None', 'None'), ('Full pump', 'Full pump'), ('Leak travel valve', 'Leak travel valve'), ('Leak standing valve', 'Leak standing valve'), ('Worn pump barrel', 'Worn pump barrel'), ('Light fluid stroke', 'Light fluid stroke'), ('Medium fluid stroke', 'Medium fluid stroke'), ('Severe fluid stroke', 'Severe fluid stroke'), ('Gas interference', 'Gas interference'), ('Shock of pump up', 'Shock of pump up'), ('Shock of pump down', 'Shock of pump down'), ('Recovering level', 'Recovering level'), ('Rods broken', 'Rods broken')], max_length=100, null=True, verbose_name='Diagnosis')),
                ('Recomendation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Good work area', 'Good work area'), ('Schedule to workover', 'Schedule to workover'), ('Unit re-spacing', 'Unit re-spacing'), ('Reduce strokes per minute', 'Reduce strokes per minute'), ('Stop pump unit', 'Stop pump unit')], max_length=100, null=True, verbose_name='Recomendation')),
            ],
            options={
                'verbose_name': 'Socker Rod Pump Data',
                'verbose_name_plural': 'All Socker Rod Pump Data',
            },
        ),
        migrations.CreateModel(
            name='TankData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Level', models.FloatField(blank=True, null=True, verbose_name='Oil Level')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tank Data',
                'verbose_name_plural': 'All Tank Data',
            },
        ),
    ]
