# Generated by Django 4.2.1 on 2025-02-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.weatherstation'),
        ),
        migrations.AddField(
            model_name='trapviewdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.trapview'),
        ),
        migrations.AddField(
            model_name='tankdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.tankdevice'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.wellanalyzerdevice'),
        ),
        migrations.AddField(
            model_name='gatewaydata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.gateway'),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.environmentaldevice'),
        ),
        migrations.AddField(
            model_name='camviddata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.camviddevice'),
        ),
    ]
