# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodpumpdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.wellanalyzerdevice'),
        ),
        migrations.AddField(
            model_name='tankdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.tankdevice'),
        ),
    ]
