# Generated by Django 5.0.6 on 2024-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity1', models.FloatField(blank=True, null=True, verbose_name='Humidity 1')),
                ('Temperature1', models.FloatField(blank=True, null=True, verbose_name='Temperature 1')),
                ('AtmosphericPressure1', models.FloatField(blank=True, null=True, verbose_name='Atmospheric Pressure 1')),
                ('Humidity2', models.FloatField(blank=True, null=True, verbose_name='Humidity 2')),
                ('Temperature2', models.FloatField(blank=True, null=True, verbose_name='Temperature 2')),
                ('AtmosphericPressure2', models.FloatField(blank=True, null=True, verbose_name='Atmospheric Pressure 2')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Environmental Data',
                'verbose_name_plural': 'All Environmental Data',
            },
        ),
    ]
