# Generated by Django 5.0.6 on 2025-03-15 13:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Diagnosis',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('None', 'None'), ('Full pump', 'Full pump'), ('Leak travel valve', 'Leak travel valve'), ('Leak standing valve', 'Leak standing valve'), ('Worn pump barrel', 'Worn pump barrel'), ('Light fluid stroke', 'Light fluid stroke'), ('Medium fluid stroke', 'Medium fluid stroke'), ('Severe fluid stroke', 'Severe fluid stroke'), ('Gas interference', 'Gas interference'), ('Shock of pump up', 'Shock of pump up'), ('Shock of pump down', 'Shock of pump down'), ('Recovering level', 'Recovering level'), ('Rods broken', 'Rods broken')], max_length=25, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Recomendation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Good work area', 'Good work area'), ('Schedule to workover', 'Schedule to workover'), ('Unit re-spacing', 'Unit re-spacing'), ('Reduce strokes per minute', 'Reduce strokes per minute'), ('Stop pump unit', 'Stop pump unit')], max_length=25, null=True, verbose_name='Recomendation'),
        ),
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped unit', 'Stopped unit')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
