# Generated by Django 5.0.6 on 2024-06-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_environmentaldata'),
        ('device', '0003_environmentaldevice_alter_tankdevice_samplingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaldata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.environmentaldevice'),
        ),
    ]
