# Generated by Django 5.0.6 on 2024-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_environmentaldata_iddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamVidData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Camera Data',
                'verbose_name_plural': 'All Camera Data',
            },
        ),
    ]
