# Generated by Django 5.0.6 on 2025-03-15 13:27

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_rodpumpdata_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Diagnosis',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'None'), ('1', 'Full pump'), ('2', 'Leak travel valve'), ('3', 'Leak standing valve'), ('4', 'Worn pump barrel'), ('5', 'Light fluid stroke'), ('6', 'Medium fluid stroke'), ('7', 'Severe fluid stroke'), ('8', 'Gas interference'), ('9', 'Shock of pump up'), ('10', 'Shock of pump down'), ('11', 'Recovering level'), ('12', 'Rods broken')], max_length=20, null=True, verbose_name='Diagnosis'),
        ),
    ]
