# Generated by Django 5.0.6 on 2024-09-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_camviddata'),
        ('device', '0008_camviddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.camviddevice'),
        ),
    ]
