# Generated by Django 4.2.20 on 2025-04-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_rodpumpdata_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodpumpdata',
            name='StrokeLength',
            field=models.FloatField(blank=True, null=True, verbose_name='Stroke Length'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='VoltageBattery',
            field=models.FloatField(blank=True, null=True, verbose_name='Voltage Battery'),
        ),
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped unit', 'Stopped unit')], max_length=25, null=True, verbose_name='Status'),
        ),
    ]
