# Generated by Django 4.2.20 on 2025-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rodpumpdata_strokelength_rodpumpdata_voltagebattery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='RunTime',
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='Refresh',
            field=models.FloatField(blank=True, null=True, verbose_name='Refresh Time'),
        ),
    ]
