# Generated by Django 5.0.6 on 2024-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_camviddata_iddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
