# Generated by Django 4.2.20 on 2025-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_rodpumpdata_runtime_rodpumpdata_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Normal running'), ('0', 'Stopped unit')], default='1', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
