# Generated by Django 4.2.20 on 2025-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_rodpumpdata_runtime_rodpumpdata_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Stopped unit')], default='1', max_length=2, null=True, verbose_name='Status'),
        ),
    ]
