# Generated by Django 4.2.20 on 2025-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_rodpumpdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Normal running'), ('0', 'Stopped unit')], default='1', max_length=2, null=True, verbose_name='Status'),
        ),
    ]
