# Generated by Django 5.0.6 on 2024-09-13 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_camviddata_classes_camviddata_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camviddata',
            name='Classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'Mariposa 1'), (1, 'Mariposa 2'), (2, 'Mariposa 3'), (3, 'Mariposa 4')]), blank=True, null=True, size=None),
        ),
    ]
