# Generated by Django 5.0.6 on 2024-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_camviddata_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='img_file_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Path'),
        ),
    ]
