# Generated by Django 5.0.6 on 2024-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_camviddata_img_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='img64',
            field=models.TextField(blank=True, null=True, verbose_name='img64'),
        ),
    ]
