# Generated by Django 5.0.6 on 2024-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_camviddata_img64'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='RainCounter',
            field=models.FloatField(blank=True, null=True, verbose_name='Rain Counter'),
        ),
        migrations.AddField(
            model_name='camviddata',
            name='VoltagePanel',
            field=models.FloatField(blank=True, null=True, verbose_name='Voltage Panel'),
        ),
        migrations.AddField(
            model_name='camviddata',
            name='WindDirection',
            field=models.FloatField(blank=True, null=True, verbose_name='Wind Direction'),
        ),
        migrations.AddField(
            model_name='camviddata',
            name='WindVelocity',
            field=models.FloatField(blank=True, null=True, verbose_name='Wind Velocity'),
        ),
    ]
