# Generated by Django 5.0.6 on 2024-10-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_camviddata_raincounter_camviddata_voltagepanel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camviddata',
            name='RainCounter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rain Counter'),
        ),
    ]
