# Generated by Django 4.2.1 on 2024-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_camviddata_raincounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='camviddata',
            name='nDetected',
            field=models.IntegerField(blank=True, null=True, verbose_name='N Detected'),
        ),
    ]
