# Generated by Django 5.0.6 on 2024-11-23 01:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_camviddata_ndetected'),
        ('device', '0020_trapview_runningnn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrapViewData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('VoltagePanel', models.FloatField(blank=True, null=True, verbose_name='Voltage Panel')),
                ('WindVelocity', models.FloatField(blank=True, null=True, verbose_name='Wind Velocity')),
                ('WindDirection', models.FloatField(blank=True, null=True, verbose_name='Wind Direction')),
                ('RainCounter', models.IntegerField(blank=True, null=True, verbose_name='Rain Counter')),
                ('Classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(0, 'Mariposa 1'), (1, 'Mariposa 2'), (2, 'Mariposa 3'), (3, 'Mariposa 4')], max_length=3, null=True, verbose_name='Class'), blank=True, null=True, size=None)),
                ('Quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('nDetected', models.IntegerField(blank=True, null=True, verbose_name='N Detected')),
                ('img64', models.TextField(blank=True, null=True, verbose_name='img64')),
                ('img_file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Path')),
                ('img_bool', models.BooleanField(default=False, verbose_name='image?')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
                ('IdDevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.trapview')),
            ],
            options={
                'verbose_name': 'Trap View Data',
                'verbose_name_plural': 'All Trap View Data',
            },
        ),
    ]
