# Generated by Django 5.0.6 on 2024-11-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_trapviewdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trapviewdata',
            name='img_file_name',
        ),
    ]
