# Generated by Django 5.0.6 on 2024-11-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_remove_trapviewdata_img_file_name'),
        ('device', '0020_trapview_runningnn'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('VoltagePanel', models.FloatField(blank=True, null=True, verbose_name='Voltage Panel')),
                ('Status', models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status')),
                ('IdDevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.camviddevice')),
            ],
            options={
                'verbose_name': 'Gateway Data',
                'verbose_name_plural': 'All Gateway Data',
            },
        ),
    ]
