# Generated by Django 5.0.6 on 2024-11-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_gatewaydata'),
        ('device', '0020_trapview_runningnn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaydata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.gateway'),
        ),
    ]
