# Generated by Django 5.0.6 on 2025-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_gatewaydata_iddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('VoltageBattery', models.FloatField(blank=True, null=True, verbose_name='Voltage Battery')),
                ('WindVelocity', models.FloatField(blank=True, null=True, verbose_name='Wind Velocity')),
                ('WindDirection', models.FloatField(blank=True, null=True, verbose_name='Wind Direction')),
                ('RainCounter', models.IntegerField(blank=True, null=True, verbose_name='Rain Counter')),
                ('Radiation', models.IntegerField(blank=True, null=True, verbose_name='Solar Radiation')),
            ],
            options={
                'verbose_name': 'Weather Station Data',
                'verbose_name_plural': 'All Weather Station Data',
            },
        ),
        migrations.RemoveField(
            model_name='trapviewdata',
            name='RainCounter',
        ),
        migrations.RemoveField(
            model_name='trapviewdata',
            name='VoltagePanel',
        ),
        migrations.RemoveField(
            model_name='trapviewdata',
            name='WindDirection',
        ),
        migrations.RemoveField(
            model_name='trapviewdata',
            name='WindVelocity',
        ),
    ]
