# Generated by Django 5.0.6 on 2025-01-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_weatherstationdata_remove_trapviewdata_raincounter_and_more'),
        ('device', '0024_weatherstation_remove_trapview_a_ws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationdata',
            name='IdDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.weatherstation'),
        ),
    ]
