# Generated by Django 5.0.6 on 2025-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_weatherstationdata_iddevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trapviewdata',
            name='Classes',
        ),
        migrations.RemoveField(
            model_name='trapviewdata',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='trapviewdata',
            name='Objective',
            field=models.CharField(blank=True, null=True, verbose_name='Plaga'),
        ),
        migrations.AlterField(
            model_name='trapviewdata',
            name='nDetected',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
