# Generated by Django 5.0.6 on 2025-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_trapviewdata_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapviewdata',
            name='nDetected',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
