# Generated by Django 5.0.6 on 2025-01-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_trapviewdata_ndetected'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
