# Generated by Django 5.0.6 on 2025-02-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_trapviewdata_ndetected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaydata',
            name='VoltagePanel',
        ),
        migrations.AddField(
            model_name='weatherstationdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gatewaydata',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trapviewdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=2, null=True, verbose_name='Status'),
        ),
    ]
