# Generated by Django 5.0.6 on 2025-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_weatherstationdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapviewdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Low battery', 'Low battery'), ('Stopped', 'Stopped')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
