# Generated by Django 5.0.6 on 2025-01-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_trapviewdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapviewdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Normal running'), ('1', 'Low battery'), ('2', 'Stopped')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
