# Generated by Django 5.0.6 on 2025-01-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LocationName', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Location Name')),
                ('Field', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
