# Generated by Django 4.2.1 on 2023-08-14 09:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodPumpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('LoadPump', models.TextField(blank=True, null=True, verbose_name='Load')),
                ('Position', models.TextField(blank=True, null=True, verbose_name='Position')),
                ('Acceleration', models.TextField(blank=True, null=True, verbose_name='Acceleration')),
                ('HeadPressure', models.FloatField(blank=True, null=True, verbose_name='Head Pressure')),
                ('HeadTemperature', models.FloatField(blank=True, null=True, verbose_name='Head Temperature')),
                ('CasingPressure', models.FloatField(blank=True, null=True, verbose_name='Casing Pressure')),
                ('ChokeOpening', models.FloatField(blank=True, null=True, verbose_name='Choke Opening')),
                ('SPM', models.FloatField(blank=True, null=True, verbose_name='SPM')),
                ('CurrentCondition', models.CharField(blank=True, max_length=20, null=True, verbose_name='Currently Condition')),
                ('Diagnosis', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('None', 'None'), ('Full pump', 'Full pump'), ('Leak travel valve', 'Leak travel valve'), ('Leak standing valve', 'Leak standing valve'), ('Worn pump barrel', 'Worn pump barrel'), ('Light fluid stroke', 'Light fluid stroke'), ('Medium fluid stroke', 'Medium fluid stroke'), ('Severe fluid stroke', 'Severe fluid stroke'), ('Gas interference', 'Gas interference'), ('Shock of pump up', 'Shock of pump up'), ('Shock of pump down', 'Shock of pump down'), ('Recovering level', 'Recovering level')], max_length=100, null=True, verbose_name='Diagnosis')),
                ('PumpFill', models.FloatField(blank=True, null=True, verbose_name='Pump Fill')),
                ('Recomendation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Good work area', 'Good work area'), ('Schedule to workover', 'Schedule to workover'), ('Unit re-spacing', 'Unit re-spacing'), ('Reduce strokes per minute', 'Reduce strokes per minute'), ('Stop pump unit', 'Stop pump unit')], max_length=100, null=True, verbose_name='Recomendation')),
                ('PumpName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
            options={
                'verbose_name': 'Socker Rod Pump Data',
                'verbose_name_plural': 'All Socker Rod Pump Data',
            },
        ),
    ]
