# Generated by Django 4.2.1 on 2023-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='Acceleration',
        ),
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='CurrentCondition',
        ),
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='HeadPressure',
        ),
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='HeadTemperature',
        ),
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='LoadPump',
        ),
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='Position',
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='DownLoad',
            field=models.TextField(blank=True, null=True, verbose_name='Down Load'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='DownPosition',
            field=models.TextField(blank=True, null=True, verbose_name='Down Position'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='RawAcceleration',
            field=models.TextField(blank=True, null=True, verbose_name='RawAcceleration'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='RunTime',
            field=models.FloatField(blank=True, null=True, verbose_name='Run Time'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='SurfaceLoad',
            field=models.TextField(blank=True, null=True, verbose_name='Surf Load'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='SurfacePosition',
            field=models.TextField(blank=True, null=True, verbose_name='Surf Position'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='TubingPressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Tubing Pressure'),
        ),
    ]
