# Generated by Django 4.2.1 on 2023-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_remove_rodpumpdata_acceleration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodpumpdata',
            name='ChokeOpening',
        ),
    ]
