# Generated by Django 4.2.1 on 2024-01-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_tankdata_rodpumpdata_pumpname_and_more'),
        ('wells', '0002_well_available_well_macaddress_well_refresh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdata',
            name='TankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.tank'),
        ),
    ]
