# Generated by Django 4.2.1 on 2023-10-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodpumpdata',
            name='TankLevel',
            field=models.FloatField(blank=True, null=True, verbose_name='SPM'),
        ),
    ]
