# Generated by Django 4.2.1 on 2023-10-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_rodpumpdata_tanklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='TankLevel',
            field=models.FloatField(blank=True, null=True, verbose_name='Tank Level'),
        ),
    ]
