# Generated by Django 4.2.1 on 2023-10-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_tank'),
        ('overview', '0006_remove_tankdata_pumpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdata',
            name='TankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.tank'),
        ),
    ]
