# Generated by Django 4.2.1 on 2023-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0007_alter_tankdata_tankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdata',
            name='Temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature'),
        ),
    ]
