# Generated by Django 4.2.1 on 2023-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_tankdata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodpumpdata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Normal running', 'Normal running'), ('Stopped unit', 'Stopped unit')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
