# Generated by Django 4.2.1 on 2023-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_alter_rodpumpdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodpumpdata',
            name='RawSurfaceLoad',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Surf Load'),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='RawSurfacePosition',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Surf Position'),
        ),
    ]
