# Generated by Django 5.0.6 on 2026-05-07 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('Type', models.CharField(choices=[('primary', 'Primaria'), ('secondary', 'Secundaria'), ('mobile', 'Móvil')], max_length=20, verbose_name='Type')),
                ('Status', models.CharField(choices=[('operational', 'Operativo'), ('maintenance', 'Mantenimiento'), ('fault', 'Falla'), ('inactive', 'Inactivo')], default='operational', max_length=20, verbose_name='Status')),
                ('NominalVoltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nominal Voltage (kV)')),
                ('InstalledCapacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installed Capacity (MVA)')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substation_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subestación',
                'verbose_name_plural': 'Subestaciones',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('Series', models.CharField(blank=True, max_length=100, verbose_name='Series')),
                ('StationName', models.CharField(max_length=150, verbose_name='Station Name')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('NominalPower', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nominal Power (kVA)')),
                ('PrimaryVoltage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Primary Voltage (V)')),
                ('SecondaryVoltage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Secondary Voltage (V)')),
                ('Type', models.CharField(choices=[('distribution', 'Distribución'), ('power', 'Potencia'), ('measurement', 'Medida'), ('autotransformer', 'Autotransformador')], max_length=20, verbose_name='Type')),
                ('CoolingType', models.CharField(choices=[('ONAN', 'ONAN'), ('ONAF', 'ONAF'), ('OFAF', 'OFAF'), ('dry', 'Seco')], default='ONAN', max_length=10, verbose_name='Cooling Type')),
                ('Manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('Model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('YearManufacture', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Manufacture')),
                ('InstallationDate', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('EstimatedLifespan', models.PositiveSmallIntegerField(default=25, verbose_name='Estimated Lifespan (years)')),
                ('Status', models.CharField(choices=[('operational', 'Operativo'), ('maintenance', 'Mantenimiento'), ('fault', 'Falla'), ('inactive', 'Inactivo')], default='operational', max_length=20, verbose_name='Status')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('Address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DateUpdate', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformer_owner', to=settings.AUTH_USER_MODEL)),
                ('Substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformers', to='TRANSFORMADOR.substation')),
            ],
            options={
                'verbose_name': 'Transformador',
                'verbose_name_plural': 'Transformadores',
                'ordering': ['-DateCreate'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Variable', models.CharField(choices=[('OilTemperature', 'Temperatura Aceite'), ('WindingTemperature', 'Temperatura Devanado'), ('LoadPercent', 'Carga %'), ('PowerFactor', 'Factor de Potencia'), ('THD', 'THD'), ('Vibration', 'Vibración'), ('Humidity', 'Humedad'), ('VoltageA', 'Voltaje A'), ('VoltageB', 'Voltaje B'), ('VoltageC', 'Voltaje C')], max_length=30, verbose_name='Variable')),
                ('Condition', models.CharField(choices=[('gt', 'Mayor que'), ('lt', 'Menor que'), ('gte', 'Mayor o igual'), ('lte', 'Menor o igual')], max_length=5, verbose_name='Condition')),
                ('Threshold', models.FloatField(verbose_name='Threshold')),
                ('Severity', models.CharField(choices=[('warning', 'Advertencia'), ('critical', 'Crítico'), ('emergency', 'Emergencia')], max_length=15, verbose_name='Severity')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('Description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('Transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='TRANSFORMADOR.transformer')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
                'ordering': ['Transformer', 'Variable'],
                'unique_together': {('Transformer', 'Variable', 'Condition')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Variable', models.CharField(max_length=100, verbose_name='Variable')),
                ('Severity', models.CharField(choices=[('warning', 'Advertencia'), ('critical', 'Crítico'), ('emergency', 'Emergencia')], max_length=15, verbose_name='Severity')),
                ('DetectedValue', models.FloatField(verbose_name='Detected Value')),
                ('ThresholdValue', models.FloatField(verbose_name='Threshold Value')),
                ('Message', models.CharField(max_length=300, verbose_name='Message')),
                ('Status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Atendida'), ('closed', 'Cerrada')], default='active', max_length=15, verbose_name='Status')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DateAcknowledged', models.DateTimeField(blank=True, null=True, verbose_name='Date Acknowledged')),
                ('DateClosed', models.DateTimeField(blank=True, null=True, verbose_name='Date Closed')),
                ('AcknowledgedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('Rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='TRANSFORMADOR.alertrule')),
                ('Transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='TRANSFORMADOR.transformer')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-DateCreate'],
            },
        ),
        migrations.CreateModel(
            name='ElectricalReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('VoltageA', models.FloatField(blank=True, null=True, verbose_name='Voltage A (V)')),
                ('VoltageB', models.FloatField(blank=True, null=True, verbose_name='Voltage B (V)')),
                ('VoltageC', models.FloatField(blank=True, null=True, verbose_name='Voltage C (V)')),
                ('CurrentA', models.FloatField(blank=True, null=True, verbose_name='Current A (A)')),
                ('CurrentB', models.FloatField(blank=True, null=True, verbose_name='Current B (A)')),
                ('CurrentC', models.FloatField(blank=True, null=True, verbose_name='Current C (A)')),
                ('ActivePower', models.FloatField(blank=True, null=True, verbose_name='Active Power (kW)')),
                ('ReactivePower', models.FloatField(blank=True, null=True, verbose_name='Reactive Power (kVAR)')),
                ('ApparentPower', models.FloatField(blank=True, null=True, verbose_name='Apparent Power (kVA)')),
                ('PowerFactor', models.FloatField(blank=True, null=True, verbose_name='Power Factor')),
                ('Frequency', models.FloatField(blank=True, null=True, verbose_name='Frequency (Hz)')),
                ('THD', models.FloatField(blank=True, null=True, verbose_name='THD (%)')),
                ('OilTemperature', models.FloatField(blank=True, null=True, verbose_name='Oil Temperature (°C)')),
                ('WindingTemperature', models.FloatField(blank=True, null=True, verbose_name='Winding Temperature (°C)')),
                ('AmbientTemperature', models.FloatField(blank=True, null=True, verbose_name='Ambient Temperature (°C)')),
                ('OilLevel', models.FloatField(blank=True, null=True, verbose_name='Oil Level (%)')),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('Vibration', models.FloatField(blank=True, null=True, verbose_name='Vibration (mm/s)')),
                ('Transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='TRANSFORMADOR.transformer')),
            ],
            options={
                'verbose_name': 'Lectura Eléctrica',
                'verbose_name_plural': 'Lecturas Eléctricas',
                'ordering': ['-DateCreate'],
                'indexes': [models.Index(fields=['Transformer', 'DateCreate'], name='TRANSFORMAD_Transfo_a705d3_idx')],
            },
        ),
    ]
