# Generated by Django 5.0.6 on 2026-05-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSFORMADOR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalreading',
            name='Humidity',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='WindingTemperature',
        ),
        migrations.AddField(
            model_name='electricalreading',
            name='HotSpotTemperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Hot Spot Devanado (°C)'),
        ),
        migrations.AddField(
            model_name='electricalreading',
            name='InternalPressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión Interna / PRD (kPa)'),
        ),
        migrations.AddField(
            model_name='electricalreading',
            name='OilHumidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Humedad en Aceite (ppm)'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='Variable',
            field=models.CharField(choices=[('OilTemperature', 'Temperatura Aceite Superior OTI (°C)'), ('HotSpotTemperature', 'Temperatura Hot Spot Devanado (°C)'), ('AmbientTemperature', 'Temperatura Ambiente (°C)'), ('InternalPressure', 'Presión Interna / PRD (kPa)'), ('OilLevel', 'Nivel de Aceite (%)'), ('Vibration', 'Vibración (mm/s)'), ('OilHumidity', 'Humedad en Aceite (ppm)'), ('LoadPercent', 'Carga %'), ('PowerFactor', 'Factor de Potencia'), ('THD', 'THD (%)'), ('VoltageA', 'Voltaje Fase A (V)'), ('VoltageB', 'Voltaje Fase B (V)'), ('VoltageC', 'Voltaje Fase C (V)')], max_length=30, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='electricalreading',
            name='AmbientTemperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Ambiente (°C)'),
        ),
        migrations.AlterField(
            model_name='electricalreading',
            name='OilLevel',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel de Aceite (%)'),
        ),
        migrations.AlterField(
            model_name='electricalreading',
            name='OilTemperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Aceite Superior OTI (°C)'),
        ),
        migrations.AlterField(
            model_name='electricalreading',
            name='Vibration',
            field=models.FloatField(blank=True, null=True, verbose_name='Vibración (mm/s)'),
        ),
    ]
