# Generated by Django 5.0.6 on 2026-05-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSFORMADOR', '0002_monitoring_variables_hotspot_pressure_oilhumidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalreading',
            name='ActivePower',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='ApparentPower',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='CurrentA',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='CurrentB',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='CurrentC',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='Frequency',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='PowerFactor',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='ReactivePower',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='THD',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='VoltageA',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='VoltageB',
        ),
        migrations.RemoveField(
            model_name='electricalreading',
            name='VoltageC',
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='Variable',
            field=models.CharField(choices=[('OilTemperature', 'Temperatura Aceite Superior OTI (°C)'), ('HotSpotTemperature', 'Temperatura Hot Spot Devanado (°C)'), ('AmbientTemperature', 'Temperatura Ambiente (°C)'), ('InternalPressure', 'Presión Interna / PRD (kPa)'), ('OilLevel', 'Nivel de Aceite (%)'), ('Vibration', 'Vibración (mm/s)'), ('OilHumidity', 'Humedad en Aceite (ppm)')], max_length=30, verbose_name='Variable'),
        ),
    ]
