# Generated by Django 5.0.6 on 2026-08-16 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('Name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del dispositivo')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('MacAddress', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC Address')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('Status', models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo'), ('Maintenance', 'Mantenimiento')], default='Active', max_length=20, verbose_name='Estado')),
                ('BuzzerState', models.CharField(blank=True, default='reposo', max_length=20, verbose_name='Buzzer')),
                ('BypassState', models.BooleanField(default=False, verbose_name='Bypass')),
                ('Temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('Humidity', models.FloatField(blank=True, null=True, verbose_name='Humedad (%)')),
                ('HasRTC', models.BooleanField(default=False, verbose_name='RTC disponible')),
                ('SDStatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado SD')),
                ('WifiOK', models.BooleanField(default=False, verbose_name='WiFi OK')),
                ('MqttOK', models.BooleanField(default=False, verbose_name='MQTT OK')),
                ('LastSeen', models.DateTimeField(blank=True, null=True, verbose_name='Última conexión')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo de seguridad',
                'verbose_name_plural': 'Dispositivos de seguridad',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerTimestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp servidor')),
                ('DeviceTimestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp dispositivo')),
                ('Origin', models.CharField(choices=[('maestro', 'Maestro'), ('esclavo', 'Esclavo')], default='maestro', max_length=20, verbose_name='Origen')),
                ('SensorIndex', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sensor (índice)')),
                ('SensorName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre sensor')),
                ('Estado', models.CharField(choices=[('normal', 'Normal'), ('activo', 'Activo')], default='normal', max_length=20, verbose_name='Estado')),
                ('Category', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('informativo', 'Informativo')], default='informativo', max_length=20, verbose_name='Categoría')),
                ('Notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seguridad.securitydevice')),
            ],
            options={
                'verbose_name': 'Evento de seguridad',
                'verbose_name_plural': 'Eventos de seguridad',
                'ordering': ['-ServerTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorKey', models.CharField(choices=[('puerta_tablero', 'Puerta tablero'), ('puerta_externa', 'Puerta externa'), ('pir1', 'PIR 1'), ('pir2', 'PIR 2'), ('pir3', 'PIR 3'), ('pir4', 'PIR 4'), ('vibracion', 'Vibración'), ('flama', 'Flama'), ('puerta_auxiliar', 'Puerta auxiliar'), ('puerta_esclavo', 'Puerta esclavo (remota)')], max_length=30, verbose_name='Clave')),
                ('Name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('SensorIndex', models.PositiveSmallIntegerField(default=0, verbose_name='Índice (payload)')),
                ('Enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('Category', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('informativo', 'Informativo')], default='critico', max_length=20, verbose_name='Categoría')),
                ('CurrentState', models.CharField(default='normal', max_length=20, verbose_name='Estado actual')),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='seguridad.securitydevice')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['SensorIndex'],
                'unique_together': {('Device', 'SensorKey')},
            },
        ),
    ]
