# Generated by Django 5.0.6 on 2026-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='Canal',
            field=models.CharField(blank=True, help_text='wifi / gprs / —', max_length=20, null=True, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='securitydevice',
            name='MqttBroker',
            field=models.CharField(blank=True, help_text='IP o hostname del broker, ej. 192.168.1.100', max_length=200, null=True, verbose_name='Broker MQTT'),
        ),
        migrations.AddField(
            model_name='securitydevice',
            name='MqttPort',
            field=models.PositiveIntegerField(default=1883, verbose_name='Puerto MQTT'),
        ),
        migrations.AddField(
            model_name='securitydevice',
            name='MqttTopic',
            field=models.CharField(blank=True, help_text='Topic MQTT, ej. seguridad/maestro01/# o seguridad/critico', max_length=300, null=True, verbose_name='Topic de escucha'),
        ),
    ]
