# Generated by Django 4.2.1 on 2023-09-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='well',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('PumpName', models.CharField(max_length=100, unique=True, verbose_name='Pump Name')),
                ('Location', models.CharField(max_length=100, verbose_name='Location')),
                ('InstallationDate', models.DateField()),
                ('InstallationComment', models.TextField(max_length=500, verbose_name='Installation Comment')),
                ('DesignStatus', models.IntegerField(blank=True, null=True, verbose_name='Design Status')),
                ('StrokeLength', models.FloatField(blank=True, null=True, verbose_name='Stroke Length')),
                ('MotorType', models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas')], default='Gas', max_length=50, verbose_name='Motor Type')),
                ('PolishedRodDiameter', models.FloatField(blank=True, null=True, verbose_name='Polished Rod Diameter')),
                ('PumpIntake', models.FloatField(blank=True, null=True, verbose_name='Pump Intake')),
                ('PlungerDiameter', models.FloatField(blank=True, null=True, verbose_name='Plunger Diameter')),
                ('TrueVerticalDepth', models.FloatField(blank=True, null=True, verbose_name='True Vertical Depth')),
                ('TotalRodLength', models.FloatField(blank=True, null=True, verbose_name='Total Rod Length')),
                ('TotalRodWeight', models.FloatField(blank=True, null=True, verbose_name='Total Rod Weight')),
                ('PumpType', models.CharField(choices=[('Sucker Rod Pump', 'Sucker Rod Pump'), ('Electrical Submersible Pump', 'Electrical Submersible Pump')], default='Sucker Rod Pump', max_length=50, verbose_name='Pump Type')),
                ('BatteryName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.battery')),
                ('FieldName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('UserAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'well',
                'verbose_name_plural': 'wells',
            },
        ),
    ]
