# Generated by Django 4.2.1 on 2024-01-18 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='Available',
            field=models.BooleanField(choices=[(True, 'available'), (False, 'not available')], default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='well',
            name='MacAddress',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mac Address'),
        ),
        migrations.AddField(
            model_name='well',
            name='Refresh',
            field=models.FloatField(blank=True, choices=[(30, '30s'), (60, '1m'), (120, '2m'), (300, '5m'), (600, '10m'), (900, '15m'), (1800, '30m')], default=120, null=True, verbose_name='Refresh'),
        ),
        migrations.AddField(
            model_name='well',
            name='Status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal'), ('not synchronized', 'not synchronized')], default='stopped', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='well',
            name='PumpType',
            field=models.CharField(choices=[('Sucker Rod Pump', 'Sucker Rod Pump'), ('Plunger Lift', 'Plunger Lift')], default='Sucker Rod Pump', max_length=50, verbose_name='Pump Type'),
        ),
        migrations.CreateModel(
            name='tank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('TankName', models.CharField(max_length=100, unique=True, verbose_name='Tank Name')),
                ('TankHeight', models.FloatField(blank=True, null=True, verbose_name='Tank Height')),
                ('TankFactor', models.FloatField(blank=True, null=True, verbose_name='Tank Factor')),
                ('Status', models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal'), ('not synchronized', 'not synchronized')], default='stopped', max_length=50, verbose_name='Status')),
                ('Refresh', models.FloatField(blank=True, choices=[(30, '30s'), (60, '1m'), (120, '2m'), (300, '5m'), (600, '10m'), (900, '15m'), (1800, '30m')], default=120, null=True, verbose_name='Refresh')),
                ('GroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('UserAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tank',
                'verbose_name_plural': 'tanks',
            },
        ),
    ]
