# Generated by Django 4.2.1 on 2023-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='MotorType',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas')], default='Gas', max_length=50, verbose_name='Motor Type'),
        ),
        migrations.AddField(
            model_name='well',
            name='PlungerDiameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Plunger Diameter'),
        ),
        migrations.AddField(
            model_name='well',
            name='PolishedRodDiameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Polished Rod Diameter'),
        ),
        migrations.AddField(
            model_name='well',
            name='PumpIntake',
            field=models.FloatField(blank=True, null=True, verbose_name='Pump Intake'),
        ),
        migrations.AddField(
            model_name='well',
            name='StrokeLength',
            field=models.FloatField(blank=True, null=True, verbose_name='Stroke Length'),
        ),
        migrations.AddField(
            model_name='well',
            name='TotalRodLength',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Rod Length'),
        ),
        migrations.AddField(
            model_name='well',
            name='TotalRodWeight',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Rod Weight'),
        ),
        migrations.AddField(
            model_name='well',
            name='TrueVerticalDepth',
            field=models.FloatField(blank=True, null=True, verbose_name='True Vertical Depth'),
        ),
    ]
