# Generated by Django 4.2.1 on 2023-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='Status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('running', 'running'), ('low battery', 'low battery'), ('no signal', 'no signal'), ('not synchronized', 'not synchronized')], default='stopped', max_length=50, verbose_name='Status'),
        ),
    ]
