# Generated by Django 4.2.1 on 2023-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0006_tank_userauthor_well_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='Available',
            field=models.BooleanField(choices=[(True, 'available'), (False, 'not available')], default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='well',
            name='MacAddress',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mac Address'),
        ),
    ]
