# Generated by Django 5.0.6 on 2026-05-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OILFIELD', '0001_initial'),
        ('device', '0007_trapview_iscontinue_trapview_sensibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='AnalyzerDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oilfield_wells', to='device.wellanalyzerdevice', verbose_name='Well Analyzer Device'),
        ),
    ]
