# Generated by Django 5.0.6 on 2026-05-20 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OILFIELD', '0002_well_analyzerdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='welldailyproduction',
            name='Tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_productions', to='OILFIELD.tank', verbose_name='Tanque receptor'),
        ),
        migrations.AddField(
            model_name='welldailyproduction',
            name='TankLevelEnd',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel tanque fin (bbl)'),
        ),
        migrations.AddField(
            model_name='welldailyproduction',
            name='TankLevelStart',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel tanque inicio (bbl)'),
        ),
        migrations.AddField(
            model_name='welldailyproduction',
            name='TankProduction',
            field=models.FloatField(blank=True, null=True, verbose_name='Producción en tanque (bbl)'),
        ),
    ]
