# Generated by Django 5.0.6 on 2026-05-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OILFIELD', '0003_welldailyproduction_tank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='welldailyproduction',
            unique_together={('Tank', 'OperativeDate')},
        ),
        migrations.AlterField(
            model_name='welldailyproduction',
            name='Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_productions', to='OILFIELD.well'),
        ),
    ]
