# Generated by Django 5.0.6 on 2026-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OILFIELD', '0004_alter_welldailyproduction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='Status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('abandoned', 'Abandonado'), ('portable', 'Portátil')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
